//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.AddressBooks = new HashSet<AddressBook>();
            this.Batches = new HashSet<Batch>();
            this.Bonus = new HashSet<Bonu>();
            this.Bonus1 = new HashSet<Bonu>();
            this.EmailVerifications = new HashSet<EmailVerification>();
            this.Notifications = new HashSet<Notification>();
            this.OrderBooks = new HashSet<OrderBook>();
            this.Orders = new HashSet<Order>();
            this.Payments = new HashSet<Payment>();
            this.ReferralHistories = new HashSet<ReferralHistory>();
            this.ReferralHistories1 = new HashSet<ReferralHistory>();
            this.UserRoles = new HashSet<UserRole>();
            this.Vouchers = new HashSet<Voucher>();
            this.Wallets = new HashSet<Wallet>();
            this.WhiteLabelAddresses = new HashSet<WhiteLabelAddress>();
        }
    
        public long AccountId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> AccountEnabled { get; set; }
        public Nullable<System.DateTime> EnableOn { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> TwoFactorEnableDate { get; set; }
        public Nullable<bool> EmailVerificationStatus { get; set; }
        public Nullable<System.DateTime> EmailVerificationDate { get; set; }
        public Nullable<int> AccountType_Id { get; set; }
        public string IdentityProofURLFront { get; set; }
        public string IdentityProofURLBack { get; set; }
        public string OtherDocuments { get; set; }
        public Nullable<int> DOBMonth { get; set; }
        public Nullable<int> DOBYear { get; set; }
        public Nullable<int> DOBDay { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<int> TotalRefferedAccounts { get; set; }
        public Nullable<long> ReferredBy { get; set; }
        public string ReferralLink { get; set; }
        public Nullable<decimal> BonusTokens { get; set; }
        public Nullable<decimal> RefferrelBonusTokens { get; set; }
        public Nullable<decimal> Tokens { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<bool> Influencer { get; set; }
        public Nullable<long> ParentID { get; set; }
        public Nullable<double> Commission { get; set; }
        public string State { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressBook> AddressBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonu> Bonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bonu> Bonus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailVerification> EmailVerifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBook> OrderBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralHistory> ReferralHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReferralHistory> ReferralHistories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wallet> Wallets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WhiteLabelAddress> WhiteLabelAddresses { get; set; }
    }
}
