//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Batch()
        {
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public long BatchId { get; set; }
        public string BatchNumber { get; set; }
        public string BatchName { get; set; }
        public string BatchDescription { get; set; }
        public Nullable<long> DistributorAccountId { get; set; }
        public Nullable<long> BatchQuantity { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
