//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bonu()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public long Id { get; set; }
        public Nullable<double> FromPercentage { get; set; }
        public Nullable<double> ToPercentage { get; set; }
        public Nullable<long> FromAccountId { get; set; }
        public Nullable<long> ToAccountId { get; set; }
        public Nullable<double> FromAmount { get; set; }
        public Nullable<double> ToAmount { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<double> ToCommission { get; set; }
        public Nullable<double> FromCommission { get; set; }
        public string Currency { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
