//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int CurrencyId { get; set; }
        public string FullName { get; set; }
        public string ThreeDigitName { get; set; }
        public Nullable<bool> IsFiat { get; set; }
        public Nullable<decimal> RateBTC { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string TxFree { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Confirms { get; set; }
        public Nullable<bool> CanConvert { get; set; }
        public string ImgURL { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string MasterPassword { get; set; }
    }
}
