//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailVerification
    {
        public long EmailVerificationId { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<long> Account_Id { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
