//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageResource
    {
        public long ResourceId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<long> LanguageId { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
