//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationId { get; set; }
        public string NotificationDetails { get; set; }
        public string NotificationHeading { get; set; }
        public string NotificationIconClass { get; set; }
        public string RedirectAction { get; set; }
        public string RedirectController { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public Nullable<long> Account_Id { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
