//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OrderId { get; set; }
        public string OrderType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> OrderStatus_Id { get; set; }
        public Nullable<long> Account_Id { get; set; }
        public Nullable<bool> IsPendingOrder { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<decimal> NetworkFee { get; set; }
        public Nullable<bool> UnderProcessed { get; set; }
        public Nullable<decimal> ProfitPercentage { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
    }
}
