//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderBook
    {
        public long OrderId { get; set; }
        public string Market { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Bid_Ask { get; set; }
        public Nullable<decimal> UnitsFilled { get; set; }
        public Nullable<decimal> TotalUnits { get; set; }
        public Nullable<decimal> ActualRate { get; set; }
        public Nullable<decimal> EstimatedTotal { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderType { get; set; }
        public Nullable<long> Account_Id { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
