//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentNotes = new HashSet<PaymentNote>();
        }
    
        public long PaymentId { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string ToWalletAddress { get; set; }
        public string PaymentType { get; set; }
        public string StatusMessage { get; set; }
        public string TransectionId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountSent { get; set; }
        public Nullable<decimal> NetworkFee { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<int> Confirms { get; set; }
        public Nullable<long> Account_Id { get; set; }
        public Nullable<int> PaymentStatus_Id { get; set; }
        public Nullable<decimal> RevenueBTC { get; set; }
        public string FiatCurrency { get; set; }
        public Nullable<decimal> FiatAmount { get; set; }
        public Nullable<long> BonusId { get; set; }
        public string SenderNote { get; set; }
        public string ReceiverNote { get; set; }
        public Nullable<bool> Note { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Bonu Bonu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentNote> PaymentNotes { get; set; }
    }
}
