//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralHistory
    {
        public long ReferralId { get; set; }
        public Nullable<long> ChildAccount { get; set; }
        public Nullable<long> ParentAccount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ReferralAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> ReferralDate { get; set; }
        public string TransactionId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
