//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Token()
        {
            this.Wallets = new HashSet<Wallet>();
        }
    
        public int TokenId { get; set; }
        public string TokenName { get; set; }
        public string TokenShortName { get; set; }
        public string TokenMasterAddress { get; set; }
        public string TokenPublicKey { get; set; }
        public string TokenPrivateKey { get; set; }
        public Nullable<decimal> TokenPriceETH { get; set; }
        public Nullable<decimal> TokenBalance { get; set; }
        public string SmartContractAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wallet> Wallets { get; set; }
    }
}
