//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public long VoucherId { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<bool> IsRedeemed { get; set; }
        public Nullable<System.DateTime> RedeemedOn { get; set; }
        public Nullable<long> BatchId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Batch Batch { get; set; }
        public virtual Voucher Vouchers1 { get; set; }
        public virtual Voucher Voucher1 { get; set; }
    }
}
