//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public long WalletId { get; set; }
        public string Currency { get; set; }
        public string WalletAddress { get; set; }
        public string BarcodeImageURL { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string WalletType { get; set; }
        public string DesTag { get; set; }
        public string PublicKey { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> BalanceStoshis { get; set; }
        public Nullable<long> Account_Id { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> RefBonus { get; set; }
        public Nullable<int> TokenId { get; set; }
        public string Mnemonics { get; set; }
        public Nullable<decimal> PendingBalance { get; set; }
        public Nullable<long> TxIndex { get; set; }
        public Nullable<bool> UnderProcessed { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Token Token { get; set; }
    }
}
