//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Woooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhiteLabelAddress
    {
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Timespan { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
